"""Add Time Limit to Quiz

Revision ID: abd8c4c617ac
Revises: bcd0a8de3c97
Create Date: 2020-03-24 12:12:43.419935

"""

# revision identifiers, used by Alembic.
revision = 'abd8c4c617ac'
down_revision = 'bcd0a8de3c97'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('time_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'time_limit')
    # ### end Alembic commands ###
