"""empty message

Revision ID: bcd0a8de3c97
Revises: 203dd50e5775
Create Date: 2017-03-07 16:05:29.460316

"""

# revision identifiers, used by Alembic.
revision = 'bcd0a8de3c97'
down_revision = '203dd50e5775'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extension', sa.Column('active', sa.Boolean(), server_default='1', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extension', 'active')
    ### end Alembic commands ###
