"""empty message

Revision ID: 459b2a3ec9e7
Revises: ff2a37151e96
Create Date: 2026-04-22 14:22:27.214234

"""

# revision identifiers, used by Alembic.
revision = "459b2a3ec9e7"
down_revision = "ff2a37151e96"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "launch_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("launch_id", sa.String(length=255), nullable=False),
        sa.Column("canvas_course_id", sa.String(length=255), nullable=True),
        sa.Column("canvas_course_name", sa.String(length=255), nullable=True),
        sa.Column("user_role", sa.String(length=50), nullable=False),
        sa.Column("launched_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("launch_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_launch_log_launch_id"), ["launch_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("launch_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_launch_log_launch_id"))

    op.drop_table("launch_log")
    # ### end Alembic commands ###
